CREATE TABLE FASES (
	ID_FASE SERIAL PRIMARY KEY,
	NOMBRE_FASE VARCHAR(100) NOT NULL
);

CREATE TABLE GRUPOS (
	ID_GRUPO SERIAL PRIMARY KEY,
	NOMBRE_GRUPO VARCHAR(100) NOT NULL
);

CREATE TABLE EQUIPOS (
	ID_EQUIPO SERIAL  PRIMARY KEY,
	NOMBRE_EQUIPO VARCHAR(100) NOT NULL,
	PAIS VARCHAR (100),
	ID_GRUPO INT ,
	FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID_GRUPO)
);

CREATE TABLE PARTIDOS (
	ID_PARTIDO SERIAL PRIMARY KEY,
	ID_FASE INT,
	FOREIGN KEY (ID_FASE) REFERENCES FASES (ID_FASE)
);

CREATE TABLE JUGADORES (
	ID_JUGADOR SERIAL PRIMARY KEY, 
	NOMBRE_JUGADOR VARCHAR(100) NOT NULL,
	NACIONALIDAD VARCHAR(100),
	ID_EQUIPO INT,
	FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO)
);

CREATE TABLE PARTIDO_EQUIPO (
	ID_PARTIDO INT ,
	ID_EQUIPO INT ,
	RESULTADO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID_PARTIDO,ID_EQUIPO),
	FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDOS (ID_PARTIDO),
	FOREIGN KEY (ID_EQUIPO)	REFERENCES EQUIPOS (ID_EQUIPO)
);