CREATE TABLE USUARIOS (
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL UNIQUE,
	ROLE VARCHAR	(100),
	CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE POSTS (
	ID SERIAL PRIMARY KEY,
	TITULO VARCHAR(100) NOT NULL,
	MENSAJE TEXT ,
	USER_ID INT ,
	ESTADO VARCHAR(100),
	CREATED_AT TIMESTAMP NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USUARIOS (ID)

);

CREATE TABLE COMENTARIOS (
	ID SERIAL PRIMARY KEY,
	COMENTARIO TEXT,
	USER_ID INT,
	POST_ID INT,
	ESTADO VARCHAR(100),
	CREATED_AT TIMESTAMP NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USUARIOS (ID),
	FOREIGN KEY (POST_ID) REFERENCES POSTS (ID)
);

CREATE TABLE SEGUIDORES (
	SEGUIDOR_USER_ID INT,
	SEGUIDO_USER_ID INT,
	CREATED_AT TIMESTAMP NOT NULL,
	FOREIGN KEY (SEGUIDOR_USER_ID) REFERENCES USUARIOS(ID),
	FOREIGN KEY (SEGUIDO_USER_ID) REFERENCES USUARIOS(ID)
);

COMMENT ON COLUMN COMENTARIOS.COMENTARIO IS 'Comentario sobre un post';
COMMENT ON COLUMN POSTS.MENSAJE IS 'Cuerpo del post';