INSERT INTO USUARIOS (USERNAME,EMAIL,ROLE,CREATED_AT)
VALUES ('JUANA', 'JUANA@GMAIL.COM','ADMINISTRADOR', CURRENT_TIMESTAMP),
	   ('RAUL', 'RAUL@GMAIL.ES', 'EDITOR',CURRENT_TIMESTAMP);
INSERT INTO POSTS (TITULO,MENSAJE,USER_ID,ESTADO,CREATED_AT)
VALUES ('PROBANDO','CORRECTO',3,'ACTIVO',CURRENT_TIMESTAMP),
	   ('PROGRAMADOR','HACER COMMIT',4,'ACTIVO',CURRENT_TIMESTAMP);
INSERT INTO COMENTARIOS (COMENTARIO,USER_ID,POST_ID,ESTADO,CREATED_AT)
VALUES ('CODIGO CORRECTO',3,1,'BORRADOR',CURRENT_TIMESTAMP),
	   ('GUARDAR CODIGO',4,2,'ENVIADO',CURRENT_TIMESTAMP);
INSERT INTO SEGUIDORES (SEGUIDOR_USER_ID,SEGUIDO_USER_ID,CREATED_AT)
VALUES (3,4,CURRENT_TIMESTAMP),
	   (4,3,CURRENT_TIMESTAMP);