INSERT INTO FASES (NOMBRE_FASE)
VALUES ('SEMIFINAL'),
		('FINAL');

INSERT INTO GRUPOS (NOMBRE_GRUPO)
VALUES ('A'),
	   ('B');
	 
INSERT INTO EQUIPOS (NOMBRE_EQUIPO,PAIS,ID_GRUPO)
VALUES ('BARCELONA','ESPAÑA',1),
	   ('REAL MADRID','ESPAÑA',2),
	   ('OLIMPIA','PARAGUAY',1),
	   ('CERRO PORTEÑO','PARAGUAY',2);
	   
INSERT INTO PARTIDOS (ID_FASE)
VALUES (1),
	   (2);

INSERT INTO JUGADORES (NOMBRE_JUGADOR,NACIONALIDAD,ID_EQUIPO)
VALUES ('MESSI','ARGENTINA',4),
	   ('RONALDO','PORTUGAL',3),
	   ('NEYMAR','BRASIL',2),
	   ('MBAPPE','FRANCIA',1);
	   
INSERT INTO PARTIDO_EQUIPO(ID_PARTIDO,ID_EQUIPO,RESULTADO)
VALUES (1,1,'1-0'),
	   (1,2,'0-1'),
	   (1,3,'5-3'),
	   (1,4,'3-5'),
	   (2,1,'3-2'),
	   (2,3,'2-3');