-- Top clientes con más facturas
SELECT C.NOMBRE||' '||C.APELLIDO "CLIENTE", COUNT(F.ID) "CANTIDAD FACTURAS"
FROM CLIENTE C JOIN FACTURA F ON C.ID=F.CLIENTE_ID
GROUP BY C.NOMBRE||' '||C.APELLIDO
ORDER BY "CANTIDAD FACTURAS" DESC
LIMIT 5;
-- Top clientes que más gastaron
SELECT C.NOMBRE||' '||C.APELLIDO "CLIENTE", SUM(FD.CANTIDAD*P.PRECIO) "MONTO"
FROM CLIENTE C 
JOIN FACTURA F ON C.ID=F.CLIENTE_ID
JOIN FACTURA_DETALLE FD ON F.ID=FD.FACTURA_ID
JOIN PRODUCTO P ON P.ID=FD.PRODUCTO_ID
GROUP BY C.NOMBRE||' '||C.APELLIDO
ORDER BY "MONTO" DESC
LIMIT 5;
-- Top monedas más utilizadas
SELECT M.NOMBRE "MONEDA", COUNT(F.MONEDA_ID) "CANTIDAD"
FROM MONEDA M 
JOIN FACTURA F ON M.ID=F.MONEDA_ID
GROUP BY M.NOMBRE
ORDER BY "CANTIDAD" DESC
LIMIT 5;
-- Top proveedor de productos
SELECT PR.RUC, PR.NOMBRE, COUNT(P.PROVEEDOR_ID) CANTIDAD
FROM PROVEEDOR PR 
JOIN PRODUCTO P ON PR.ID=P.PROVEEDOR_ID
GROUP BY PR.RUC, PR.NOMBRE
ORDER BY CANTIDAD DESC
LIMIT 5;
-- Productos más vendidos
SELECT P.NOMBRE, SUM(FD.CANTIDAD) CANTIDAD
FROM PRODUCTO P 
JOIN FACTURA_DETALLE FD ON P.ID=FD.PRODUCTO_ID
GROUP BY P.NOMBRE
ORDER BY CANTIDAD DESC
LIMIT 5;
-- Productos menos vendidos
SELECT P.NOMBRE, SUM(FD.CANTIDAD) CANTIDAD
FROM PRODUCTO P 
JOIN FACTURA_DETALLE FD ON P.ID=FD.PRODUCTO_ID
GROUP BY P.NOMBRE
ORDER BY CANTIDAD ASC
LIMIT 5;
/*Consulta que muestra fecha de emisión de factura, nombre y apellido del
cliente, nombres de productos de esa factura, cantidades compradas,
nombre de tipo de factura de una factura específica
robamos con la factura_id = 97*/
SELECT F.FECHA_EMISION FECHA, C.NOMBRE||' '||C.APELLIDO CLIENTES,
       P.NOMBRE PRODUCTOS , FD.CANTIDAD CANTIDAD_COMPRADAS,
	   FT.NOMBRE TIPO_FACTURA
FROM CLIENTE C 
JOIN FACTURA F ON F.CLIENTE_ID=C.ID
JOIN FACTURA_TIPO FT ON F.FACTURA_TIPO_ID=FT.ID
JOIN FACTURA_DETALLE FD ON F.ID=FD.FACTURA_ID
JOIN PRODUCTO P ON P.ID=FD.PRODUCTO_ID
WHERE FD.FACTURA_ID = 97;
/*Montos de facturas ordenados según totales
Mostrar el IVA del 10% de los montos totales de facturas
(suponer que todos los productos tienen IVA del 10%)*/
SELECT FD.FACTURA_ID, SUM(FD.CANTIDAD*P.PRECIO) "MONTO TOTAL", 
       SUM(FD.CANTIDAD*P.PRECIO)*0.10 "IVA 10%"
FROM PRODUCTO P 
JOIN FACTURA_DETALLE FD ON FD.PRODUCTO_ID=P.ID
GROUP BY FD.FACTURA_ID
ORDER BY "MONTO TOTAL" DESC;