CREATE TABLE FASES (
	ID_FASE SERIAL PRIMARY KEY,
	NOMBRE_FASE VARCHAR(100) NOT NULL
);

CREATE TABLE GRUPOS (
	ID_GRUPO SERIAL PRIMARY KEY,
	NOMBRE_GRUPO VARCHAR(100) NOT NULL
);

CREATE TABLE EQUIPOS (
	ID_EQUIPO SERIAL  PRIMARY KEY,
	NOMBRE_EQUIPO VARCHAR(100) NOT NULL,
	PAIS VARCHAR (100),
	ID_GRUPO INT ,
	FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID_GRUPO)
);

CREATE TABLE PARTIDOS (
	ID_PARTIDO SERIAL PRIMARY KEY,
	ID_FASE INT,
	FOREIGN KEY (ID_FASE) REFERENCES FASES (ID_FASE)
);

CREATE TABLE JUGADORES (
	ID_JUGADOR SERIAL PRIMARY KEY, 
	NOMBRE_JUGADOR VARCHAR(100) NOT NULL,
	NACIONALIDAD VARCHAR(100),
	ID_EQUIPO INT,
	FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO)
);

CREATE TABLE PARTIDO_EQUIPO (
	ID_PARTIDO INT ,
	ID_EQUIPO INT ,
	RESULTADO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID_PARTIDO,ID_EQUIPO),
	FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDOS (ID_PARTIDO),
	FOREIGN KEY (ID_EQUIPO)	REFERENCES EQUIPOS (ID_EQUIPO)
);

INSERT INTO FASES (NOMBRE_FASE)
VALUES ('SEMIFINAL'),
		('FINAL');

INSERT INTO GRUPOS (NOMBRE_GRUPO)
VALUES ('A'),
	   ('B');
	 
INSERT INTO EQUIPOS (NOMBRE_EQUIPO,PAIS,ID_GRUPO)
VALUES ('BARCELONA','ESPAÑA',1),
	   ('REAL MADRID','ESPAÑA',2),
	   ('OLIMPIA','PARAGUAY',1),
	   ('CERRO PORTEÑO','PARAGUAY',2);
	   
INSERT INTO PARTIDOS (ID_FASE)
VALUES (1),
	   (2);

INSERT INTO JUGADORES (NOMBRE_JUGADOR,NACIONALIDAD,ID_EQUIPO)
VALUES ('MESSI','ARGENTINA',4),
	   ('RONALDO','PORTUGAL',3),
	   ('NEYMAR','BRASIL',2),
	   ('MBAPPE','FRANCIA',1);
	   
INSERT INTO PARTIDO_EQUIPO(ID_PARTIDO,ID_EQUIPO,RESULTADO)
VALUES (1,1,'1-0'),
	   (1,2,'0-1'),
	   (1,3,'5-3'),
	   (1,4,'3-5'),
	   (2,1,'3-2'),
	   (2,3,'2-3');
	   
INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, ID_EQUIPO)
VALUES ('ALMIRON','PARAGUAY',4),
	   ('ENCISO', 'PARAGUAY',4),
	   ('ROQUE', 'PARAGUAY',3);
	   
DELETE FROM JUGADORES WHERE ID_JUGADOR = 7;

ALTER TABLE JUGADORES ADD COLUMN GOLES INT;

UPDATE JUGADORES 
SET GOLES = 900
WHERE ID_JUGADOR = 1;

UPDATE JUGADORES 
SET GOLES = 700
WHERE ID_JUGADOR = 2;

UPDATE JUGADORES 
SET GOLES = 500
WHERE ID_JUGADOR = 3;

UPDATE JUGADORES 
SET GOLES = 300
WHERE ID_JUGADOR = 4;

UPDATE JUGADORES 
SET GOLES = 200
WHERE ID_JUGADOR = 5;

UPDATE JUGADORES 
SET GOLES = 100
WHERE ID_JUGADOR = 6;